# Generated by Django 2.1.7 on 2019-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='balances',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balances',
            name='amt_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balances',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balances',
            name='name',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
