# Generated by Django 2.1.7 on 2019-04-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190409_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
